<!DOCTYPE html>
<html>
<head>
<title>Balance Sheet</title>

	<!-- fevicon -->
 	<link rel="shortcut icon" href="${pageContext.request.contextPath}/resources/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="${pageContext.request.contextPath}/resources/images/favicon.ico" type="image/x-icon">
    
    <script>
    if (localStorage.status==undefined) window.location.href='${pageContext.request.contextPath}/index/logout'; //logout user incase status is undefined
    </script>
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<style>
	table {
    border-collapse: collapse;
	}

	table, th, td {
    	border: 1px solid black;
	}
</style>

    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/css/cancel_ticket.css">

</head>
<body style="background-image: url(${pageContext.request.contextPath}/resources/images/TS_BG_03.jpg)">
	<div class="container nopadding">

	<!-- header -->
		<div class="row hidden-print hidden-xs">
			<div class="col-sm-12 header" style=" min-width: 102%;">
				<div class="row">
					<div class="col-xs-2" style="margin-left: 1%">
						<img src="${pageContext.request.contextPath}/resources/images/TS_Logo_hdpi.png" class="pull-left" height="52" width="225"/>
					</div>
					<div class="col-xs-5">
							<h4 class="heading" style="font-size: 0.9em">Short/ Excess Sheet</h4>
						<div></div>
					</div>
					<div class="col-xs-4" style="position: relative; top: 25px; left: 40px;">
						<span style="margin-right: 10px;"><!--Contact: 9999999999--></span>
						<input type="button" value="Signout" class="signout" onclick="localStorage.clear();window.location.href='${pageContext.request.contextPath}/index/logout';">
					</div>
				</div>
			</div>
		</div>
		
		<div class="visible-xs container hidden-print" style="margin: 0px; padding: 0px">
		
				<div class="row">
					<div class="col-xs-12" style="background-color: #ee9620">
						<img src='${pageContext.request.contextPath}/resources/images/TS_Logo_hdpi.png' alt='TollSecure - Securing Toll Business' style="margin-left: 15%; margin-bottom: 10%" width="60%"/>
						<input type="image" src="${pageContext.request.contextPath}/resources/images/mono-logout.svg" alt="Signout" width="28" height="28" style="margin-left: 15%" onclick="localStorage.clear();window.location.href='${pageContext.request.contextPath}/index/logout';">
						<br><span style="margin-left:20%">Short/ Excess Sheet</span>
					</div>
				</div>
		</div>	

	<div class="row">
			<div class="col-sm-12 black_header hidden-print">
				<div class="col-md-3">
					<a href='javascript:history.back()' style="background: url(${pageContext.request.contextPath}/resources/images/left.png) 0; margin-left: -220px"><span style="margin-left: -87px">Back</span></a>
				</div>

				<div class="col-md-4">
					
				</div>

				<div class="col-md-5">
					<!-- <label>Ticket Number. </label><input type="number" value="" id="tno" class="head_inp" name="">
					<input type="button" class="inp1" value="Search" onclick="searchTicket()">
					<div class="error" id="terror">Please enter a valid ticket number</div> -->
				</div>
			</div>
		</div>


		<div class="row" style="min-height: 450px">
			<div id="demo" class="col-md-10 maincontent col-md-offset-2" style="margin-top: 5%;" style="backgroundcolor:#fff">

		<div class="visible-print">
			<img src='${pageContext.request.contextPath}/resources/images/nhai-logo.jpg' align='left' width='100px'/>
		</div>
		<table style="margin-left: 10px;">
			<tr>
				<td>
					<b>Date.</b> 
				</td>

				<td>
					<b>LaneId.</b>
				</td>

				<td>
					<b>shift Desc.</b> 
				</td>

				<td>
					<b>userId.</b> 
				</td>

				<td>
					<b>Generated By.</b> 
				</td>

			</tr>
			<tr>
				<td>
					${date}
				</td>
	
				<td>
					 ${laneId}
				</td>
				
				<td>
					${shiftDesc}
				</td>
				
				<td>
					${userId}
				</td>
								
				<td>
					${userFromSession.userFirstName}
				</td>
			</tr>
		</table><br>
				
				
				<table style="margin-left: 10px;">
					<tr>
						<th>VEHICLE_CLASS</th>
						<th>VEHICLE COUNT</th>
						<th>VEHICLE AMOUNT</th>
					</tr>
					<tr>
						<td>CAR/ JEEP</td>
						<td>${car_jeep_count}</td>
						<td>${car_jeep_tot}</td>
					</tr>
					
					<tr>
						<td>LCV</td>
						<td>${lcv_count}</td>
						<td>${lcv_tot}</td>
					</tr>
					
					<tr>
						<td>BUS/ TRUCK</td>
						<td>${bus_truck_count}</td>
						<td>${bus_truck_tot}</td>
					</tr>
					
					<tr>
						<td>3 AXEL</td>
						<td>${_3_axel_count}</td>
						<td>${_3_axel_tot}</td>
					</tr>
					
					<tr>
						<td>HCM/ MAV</td>
						<td>${hcm_mav_count}</td>
						<td>${hcm_mav_tot}</td>
					</tr>
					
					<tr>
						<td>OVERSIZED</td>
						<td>${oversized_count}</td>
						<td>${oversized_tot}</td>
					</tr>
				</table>
				<br>
				<table>
					<tr>
						<th>Rs 2000</th>
						<th>Rs 1000</th>
						<th>Rs 500</th>
						<th>Rs 200</th>
						<th>Rs 100</th>
						<th>Rs 50</th>
						<th>Rs 20</th>
						<th>Rs 10</th>
						<th>Rs 5</th>
						<th>Rs 2</th>
						<th>Rs 1</th>
						<th>Total Count</th>
						<th>Amount</th>
					</tr>
					
					<tr>
						<td>${d2000}</td>
						<td>${d1000}</td>
						<td>${d500}</td>
						<td>${d200}</td>
						<td>${d100}</td>
						<td>${d50}</td>
						<td>${d20}</td>
						<td>${d10}</td>
						<td>${d5}</td>
						<td>${d2}</td>
						<td>${d1}</td>
						<td>${totalCount}</td>
						<td>${total}</td>
					</tr>
				</table>
				
				<br>
				<table>
					<tr>
						<th>Date</th>
						<th>Shift</tcol-offset-md-2h>
						<th>Total Form Transactions Data</th>
						<th>Total Amount cashed up</th>
						<th>Floating Amount</th>
						<th>Excess</th>
						<th>Short</th>
					</tr>
					
					<tr>
						<td>${date}</td>
						<td>${shiftDesc}</td>
						<td>${transactionTotal}</td>
						<td>${total}</td>
						<td>${floatingAmount}</td>
						<td>${excess}</td>
						<td>${shorti}</td>
					</tr>
					
				</table>
				
				
			</div>
		</div>
	</div>
</body>
</html>